name: devworld
version: "1.0.0"

profile: devworld

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - target
  - dbt_packages

models:
  devworld:
    bronze:
      +database: devworld_lake
      +schema: bronze
      +materialized: view
    silver:
      +database: devworld_lake
      +schema: silver
      +materialized: table
    gold:
      +database: devworld_lake
      +schema: gold
      +materialized: table
    github_gold:
      +database: devworld_lake
      +schema: github_gold
      +materialized: table
    reverse_etl:
      +database: app_db
      +schema: serving
      +materialized: table
