from __future__ import annotations

from typing import Protocol

from src.domain.entities.article import Article
from src.domain.entities.crawl_job import CrawlJob
from src.domain.entities.crawl_source import CrawlSource


class ArticleRepository(Protocol):
    def save(self, article: Article) -> None: ...

    def find_by_id(self, article_id: str) -> Article | None: ...

    def find_by_url(self, url: str) -> Article | None: ...

    def find_by_source(self, source_id: str) -> list[Article]: ...

    def exists_by_url(self, url: str) -> bool: ...


class CrawlSourceRepository(Protocol):
    def save(self, source: CrawlSource) -> None: ...

    def find_by_id(self, source_id: str) -> CrawlSource | None: ...

    def find_by_name(self, name: str) -> CrawlSource | None: ...

    def find_active(self) -> list[CrawlSource]: ...


class CrawlJobRepository(Protocol):
    def save(self, job: CrawlJob) -> None: ...

    def find_by_id(self, job_id: str) -> CrawlJob | None: ...

    def update_status(self, job_id: str, status: str) -> None: ...

    def find_by_source_and_date(
        self, source_id: str, partition_date: str
    ) -> CrawlJob | None: ...
